/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AplikasiPenjualan;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class PaymentForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form PaymentForm
     */
    public PaymentForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alamatButtonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        orderNameTxt = new javax.swing.JTextField();
        jenisCombobox = new javax.swing.JComboBox<>();
        priceBarangTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ongkirTxt = new javax.swing.JTextField();
        jarakCombo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        totalTxt = new javax.swing.JTextField();
        processButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        bwsRadioButton = new javax.swing.JRadioButton();
        luarbwsRadioButton = new javax.swing.JRadioButton();

        setTitle("FORM PENJUALAN");

        jLabel1.setText("Nama Pemesan");

        jLabel2.setText("Jenis Barang");

        jLabel3.setText("Harga Barang");

        jenisCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- PILIH ---", "LEMARI BAJU", "RAK PIRING", "ETALASE", "JEMURAN BAJU" }));
        jenisCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenisComboboxActionPerformed(evt);
            }
        });

        priceBarangTxt.setEditable(false);
        priceBarangTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AplikasiPenjualan/gambar.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");

        jLabel7.setText("Ongkos Kirim");

        ongkirTxt.setEditable(false);
        ongkirTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ongkirTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ongkirTxtActionPerformed(evt);
            }
        });

        jarakCombo.setText("Alamat Pemesan");

        jLabel9.setText("Total Bayar");

        totalTxt.setEditable(false);
        totalTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        processButton.setText("PROSES");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });

        saveButton.setText("SIMPAN");

        deleteButton.setText("HAPUS");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        alamatButtonGroup.add(bwsRadioButton);
        bwsRadioButton.setText("Bondowoso");
        bwsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bwsRadioButtonActionPerformed(evt);
            }
        });

        alamatButtonGroup.add(luarbwsRadioButton);
        luarbwsRadioButton.setText("Luar Bondowoso");
        luarbwsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luarbwsRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ongkirTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(priceBarangTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(saveButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jenisCombobox, 0, 151, Short.MAX_VALUE)
                            .addComponent(orderNameTxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jarakCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(luarbwsRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bwsRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(processButton)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(orderNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jenisCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(priceBarangTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jarakCombo)
                            .addComponent(bwsRadioButton))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(luarbwsRadioButton)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ongkirTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(totalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(processButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(deleteButton))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jenisComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenisComboboxActionPerformed
        switch(jenisCombobox.getSelectedIndex()){
            case 0:
                priceBarangTxt.setText("");
                ongkirTxt.setText("");
                totalTxt.setText("");
                alamatButtonGroup.clearSelection();
                break;
                
            case 1:
                priceBarangTxt.setText("1600000");
                ongkirTxt.setText("");
                totalTxt.setText("");
                alamatButtonGroup.clearSelection();
                break;
            
            case 2:
                priceBarangTxt.setText("500000");
                ongkirTxt.setText("");
                totalTxt.setText("");
                alamatButtonGroup.clearSelection();
                break;
                
            case 3:
                priceBarangTxt.setText("1500000");
                ongkirTxt.setText("");
                totalTxt.setText("");
                alamatButtonGroup.clearSelection();
                break;
                
            default:
                priceBarangTxt.setText("650000");
                ongkirTxt.setText("");
                totalTxt.setText("");
                alamatButtonGroup.clearSelection();
                break;   
        }
    }//GEN-LAST:event_jenisComboboxActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        orderNameTxt.setText("");
        priceBarangTxt.setText("");
        ongkirTxt.setText("");
        totalTxt.setText("");
        jenisCombobox.setSelectedIndex(0);
        alamatButtonGroup.clearSelection();
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void ongkirTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ongkirTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ongkirTxtActionPerformed

    private void bwsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bwsRadioButtonActionPerformed
        if(jenisCombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih jenis barang terlebih dahulu");
            alamatButtonGroup.clearSelection();
        }else
        ongkirTxt.setText("50000");
        
        totalTxt.setText("");
        
    }//GEN-LAST:event_bwsRadioButtonActionPerformed

    private void luarbwsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luarbwsRadioButtonActionPerformed
        if(jenisCombobox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pilih jenis barang terlebih dahulu");
            alamatButtonGroup.clearSelection();
        }else
        ongkirTxt.setText("100000");
        
        totalTxt.setText("");
        
    }//GEN-LAST:event_luarbwsRadioButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
       if(orderNameTxt.getText().isEmpty()){
          JOptionPane.showMessageDialog(null, "Isian belum lengkap");
       }else if(priceBarangTxt.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "pilih jenis barang");
       }else if(ongkirTxt.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Pilih alamat pemesan");
       }else{
        //long pricebarang, ongkir, totalbayar;
        long pricebarang = Long.parseLong(priceBarangTxt.getText()),
        ongkir = Long.parseLong(ongkirTxt.getText()),
                totalbayar;
        
        totalbayar = (pricebarang + ongkir);
        totalTxt.setText("" +totalbayar);
       }         
                
    }//GEN-LAST:event_processButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup alamatButtonGroup;
    private javax.swing.JRadioButton bwsRadioButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jarakCombo;
    private javax.swing.JComboBox<String> jenisCombobox;
    private javax.swing.JRadioButton luarbwsRadioButton;
    private javax.swing.JTextField ongkirTxt;
    private javax.swing.JTextField orderNameTxt;
    private javax.swing.JTextField priceBarangTxt;
    private javax.swing.JButton processButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField totalTxt;
    // End of variables declaration//GEN-END:variables
}
